"""Reference table of the 114 surahs.

Each row: (number, arabic_name, latin_name, indonesian_translation).
Surah slug (used in practice item ids like ``ad_dhuha_1``) is derived from
the latin name in ``surah_slug``.
"""

from __future__ import annotations

# fmt: off
_SURAHS: list[tuple[int, str, str, str]] = [
    (1, "الفاتحة", "Al-Fatihah", "Pembukaan"),
    (2, "البقرة", "Al-Baqarah", "Sapi Betina"),
    (3, "آل عمران", "Ali 'Imran", "Keluarga Imran"),
    (4, "النساء", "An-Nisa", "Wanita"),
    (5, "المائدة", "Al-Ma'idah", "Jamuan"),
    (6, "الأنعام", "Al-An'am", "Hewan Ternak"),
    (7, "الأعراف", "Al-A'raf", "Tempat-tempat Tinggi"),
    (8, "الأنفال", "Al-Anfal", "Rampasan Perang"),
    (9, "التوبة", "At-Taubah", "Pengampunan"),
    (10, "يونس", "Yunus", "Yunus"),
    (11, "هود", "Hud", "Hud"),
    (12, "يوسف", "Yusuf", "Yusuf"),
    (13, "الرعد", "Ar-Ra'd", "Guruh"),
    (14, "إبراهيم", "Ibrahim", "Ibrahim"),
    (15, "الحجر", "Al-Hijr", "Al-Hijr"),
    (16, "النحل", "An-Nahl", "Lebah"),
    (17, "الإسراء", "Al-Isra", "Perjalanan Malam"),
    (18, "الكهف", "Al-Kahf", "Penghuni Gua"),
    (19, "مريم", "Maryam", "Maryam"),
    (20, "طه", "Taha", "Taha"),
    (21, "الأنبياء", "Al-Anbiya", "Nabi-Nabi"),
    (22, "الحج", "Al-Hajj", "Haji"),
    (23, "المؤمنون", "Al-Mu'minun", "Orang-orang Mukmin"),
    (24, "النور", "An-Nur", "Cahaya"),
    (25, "الفرقان", "Al-Furqan", "Pembeda"),
    (26, "الشعراء", "Asy-Syu'ara", "Penyair"),
    (27, "النمل", "An-Naml", "Semut"),
    (28, "القصص", "Al-Qasas", "Cerita"),
    (29, "العنكبوت", "Al-'Ankabut", "Laba-laba"),
    (30, "الروم", "Ar-Rum", "Bangsa Romawi"),
    (31, "لقمان", "Luqman", "Luqman"),
    (32, "السجدة", "As-Sajdah", "Sajdah"),
    (33, "الأحزاب", "Al-Ahzab", "Golongan yang Bersekutu"),
    (34, "سبأ", "Saba", "Saba"),
    (35, "فاطر", "Fatir", "Pencipta"),
    (36, "يس", "Yasin", "Yasin"),
    (37, "الصافات", "As-Saffat", "Barisan-barisan"),
    (38, "ص", "Sad", "Sad"),
    (39, "الزمر", "Az-Zumar", "Rombongan"),
    (40, "غافر", "Ghafir", "Yang Mengampuni"),
    (41, "فصلت", "Fussilat", "Yang Dijelaskan"),
    (42, "الشورى", "Asy-Syura", "Musyawarah"),
    (43, "الزخرف", "Az-Zukhruf", "Perhiasan"),
    (44, "الدخان", "Ad-Dukhan", "Kabut"),
    (45, "الجاثية", "Al-Jasiyah", "Yang Berlutut"),
    (46, "الأحقاف", "Al-Ahqaf", "Bukit-bukit Pasir"),
    (47, "محمد", "Muhammad", "Muhammad"),
    (48, "الفتح", "Al-Fath", "Kemenangan"),
    (49, "الحجرات", "Al-Hujurat", "Kamar-kamar"),
    (50, "ق", "Qaf", "Qaf"),
    (51, "الذاريات", "Az-Zariyat", "Angin yang Menerbangkan"),
    (52, "الطور", "At-Tur", "Bukit"),
    (53, "النجم", "An-Najm", "Bintang"),
    (54, "القمر", "Al-Qamar", "Bulan"),
    (55, "الرحمن", "Ar-Rahman", "Yang Maha Pengasih"),
    (56, "الواقعة", "Al-Waqi'ah", "Hari Kiamat"),
    (57, "الحديد", "Al-Hadid", "Besi"),
    (58, "المجادلة", "Al-Mujadalah", "Hujjah"),
    (59, "الحشر", "Al-Hasyr", "Pengusiran"),
    (60, "الممتحنة", "Al-Mumtahanah", "Wanita yang Diuji"),
    (61, "الصف", "As-Saff", "Satu Barisan"),
    (62, "الجمعة", "Al-Jumu'ah", "Hari Jumat"),
    (63, "المنافقون", "Al-Munafiqun", "Orang-orang Munafik"),
    (64, "التغابن", "At-Tagabun", "Hari Pembalasan"),
    (65, "الطلاق", "At-Talaq", "Perceraian"),
    (66, "التحريم", "At-Tahrim", "Mengharamkan"),
    (67, "الملك", "Al-Mulk", "Kerajaan"),
    (68, "القلم", "Al-Qalam", "Pena"),
    (69, "الحاقة", "Al-Haqqah", "Hari Kiamat"),
    (70, "المعارج", "Al-Ma'arij", "Tempat Naik"),
    (71, "نوح", "Nuh", "Nuh"),
    (72, "الجن", "Al-Jinn", "Jin"),
    (73, "المزمل", "Al-Muzzammil", "Yang Berselimut"),
    (74, "المدثر", "Al-Muddassir", "Yang Berkemul"),
    (75, "القيامة", "Al-Qiyamah", "Hari Kebangkitan"),
    (76, "الإنسان", "Al-Insan", "Manusia"),
    (77, "المرسلات", "Al-Mursalat", "Yang Diutus"),
    (78, "النبأ", "An-Naba", "Berita Besar"),
    (79, "النازعات", "An-Nazi'at", "Malaikat Pencabut"),
    (80, "عبس", "'Abasa", "Bermuka Masam"),
    (81, "التكوير", "At-Takwir", "Penggulungan"),
    (82, "الإنفطار", "Al-Infitar", "Terbelah"),
    (83, "المطففين", "Al-Mutaffifin", "Yang Curang"),
    (84, "الإنشقاق", "Al-Insyiqaq", "Terbelah"),
    (85, "البروج", "Al-Buruj", "Gugusan Bintang"),
    (86, "الطارق", "At-Tariq", "Yang Datang di Malam Hari"),
    (87, "الأعلى", "Al-A'la", "Yang Paling Tinggi"),
    (88, "الغاشية", "Al-Gasyiyah", "Hari Pembalasan"),
    (89, "الفجر", "Al-Fajr", "Fajar"),
    (90, "البلد", "Al-Balad", "Negeri"),
    (91, "الشمس", "Asy-Syams", "Matahari"),
    (92, "الليل", "Al-Lail", "Malam"),
    (93, "الضحى", "Ad-Duha", "Waktu Duha"),
    (94, "الشرح", "Asy-Syrah", "Melapangkan"),
    (95, "التين", "At-Tin", "Buah Tin"),
    (96, "العلق", "Al-'Alaq", "Segumpal Darah"),
    (97, "القدر", "Al-Qadr", "Kemuliaan"),
    (98, "البينة", "Al-Bayyinah", "Bukti Nyata"),
    (99, "الزلزلة", "Az-Zalzalah", "Kegoncangan"),
    (100, "العاديات", "Al-'Adiyat", "Kuda Berlari Kencang"),
    (101, "القارعة", "Al-Qari'ah", "Hari Kiamat"),
    (102, "التكاثر", "At-Takasur", "Bermegah-megahan"),
    (103, "العصر", "Al-'Asr", "Masa"),
    (104, "الهمزة", "Al-Humazah", "Pengumpat"),
    (105, "الفيل", "Al-Fil", "Gajah"),
    (106, "قريش", "Quraisy", "Suku Quraisy"),
    (107, "الماعون", "Al-Ma'un", "Bantuan Kecil"),
    (108, "الكوثر", "Al-Kausar", "Nikmat Berlimpah"),
    (109, "الكافرون", "Al-Kafirun", "Orang-orang Kafir"),
    (110, "النصر", "An-Nasr", "Pertolongan"),
    (111, "المسد", "Al-Lahab", "Gejolak Api"),
    (112, "الإخلاص", "Al-Ikhlas", "Ikhlas"),
    (113, "الفلق", "Al-Falaq", "Waktu Subuh"),
    (114, "الناس", "An-Nas", "Manusia"),
]
# fmt: on


def surah_slug(latin_name: str) -> str:
    return latin_name.lower().replace("'", "").replace("-", "_").replace(" ", "_").replace(".", "")


SURAH_BY_NUMBER: dict[int, dict] = {
    number: {
        "number": number,
        "arabic_name": arabic,
        "latin_name": latin,
        "translation": translation,
        "slug": surah_slug(latin),
    }
    for number, arabic, latin, translation in _SURAHS
}
